version: '3'

services:
    pci-training-reverse-proxy:
        container_name: pci-training-reverse-proxy
        image: traefik:v1.7
        command: --api --docker
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - ./traefik.toml:/etc/traefik/traefik.toml
            - ./certs:/certs
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - pci-docker

    pci-training-nginx:
        container_name: pci-training-nginx
        image: nginx:stable
        networks:
            - pci-training
            - pci-docker
        volumes:
            - ../tao:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
        working_dir: /etc/nginx/conf.d
        labels:
            - "traefik.backend=pci-training-nginx"
            - "traefik.frontend.rule=Host:training.pci.localhost"
            - "traefik.docker.network=pci-docker"
            - "traefik.port=80"

    pci-training-phpfpm:
        container_name: pci-training-phpfpm
        build:
            context: ./docker/phpfpm
        expose:
            - 9000
        networks:
            - pci-training
            - pci-docker
        volumes:
            - ../tao:/var/www/html
            - ./volume:/var/stack
        working_dir: /var/www/html
        environment:
            XDEBUG_CONFIG: remote_enable=On remote_host=host.docker.localhost remote_port=9000
            PHP_IDE_CONFIG: serverName=training.pci.localhost

    pci-training-mariadb:
        container_name: pci-training-mariadb
        image: mariadb:latest
        networks:
            - pci-training
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: r00t
            MYSQL_USER: pci-training
            MYSQL_PASSWORD: pci-training
            MYSQL_DATABASE: pci-training
        volumes:
            - pci-training-mariadb_data:/var/lib/mysql:cached

volumes:
    pci-training-mariadb_data:
        driver: local

networks:
    pci-training:
        driver: bridge
    pci-docker:
        external: true
